server:
  port: 80 # 网关端口
spring:
  application:
    name: opentool-gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: opentool-dashboard # 路由id
#          uri: http://127.0.0.1:8089
          uri: lb://opentool-dashboard # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/dashboard/** # 这个是按照路径匹配，只要以/dashboard/开头就符合要求
      globalcors: # 全局的跨域请求
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5173"
            allowedMethods: # 允许的跨域ajax的请求方法
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带头信息
            allowCredentials: true # 是否允许携带cookie信息
            maxAge: 360000 # 这次跨域检测的有效期
